version: "3.8"
services: 

  backend: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_ROOT_DSN=postgresql://postgres:postgres@postgres-db/postgres
      - POSTGRES_DSN=postgresql://postgres:postgres@postgres-db/dido
      - POSTGRES_TEST_DSN=postgresql://postgres:postgres@postgres-db/dido_test
      - BROKER_URL = "redis://redis:6379/0"
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on: 
      - "redis"
      - "postgres-db"

  redis: 
    image: "redis:alpine"
    ports:
      - "8002:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_entrypoint worker --loglevel=info
    environment:
      - POSTGRES_ROOT_DSN=postgresql://postgres:postgres@postgres-db/postgres
      - POSTGRES_DSN=postgresql://postgres:postgres@postgres-db/dido
      - POSTGRES_TEST_DSN=postgresql://postgres:postgres@postgres-db/dido_test
      - BROKER_URL = "redis://redis:6379/0"
    depends_on: 
      - "redis"
      - "postgres-db"
    ports:
      - "8003:8000"

  postgres-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data # To persist content
    ports:
      - "8004:5432"
    command: ["postgres", "-c", "log_statement=all"]


volumes:
  database-data:



