version: "3.8"
services:
  redis:
    image: "redis:6.0.10-alpine"
    networks:
      - default

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    working_dir: /app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    ports:
      - "${BACKEND_PORT-8000}:80"
    networks:
      - default

  celeryworker:
    image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: celeryworker.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    networks:
      - default

