version: "3.8"
services: 
  redis: 
    image: "redis:6.0.10-alpine"
    networks:
      - default

  backend:
    depends_on: 
      - "redis"
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    working_dir: /app
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    ports: 
      - "80:80"
    networks:
      - default

  celeryworker:
    depends_on: 
      - "redis"
    build:
      context: .
      dockerfile: celeryworker.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    networks:
      - default

volumes:
  database-data:
