version: "3.8"
services:
  redis:
    image: "redis:6.0.10-alpine"
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    working_dir: /app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - JOBS_BASE_PATH=${JOBS_BASE_PATH_MOUNT}
    volumes:
      - $JOBS_BASE_PATH_HOST:$JOBS_BASE_PATH_MOUNT
    ports:
      - "${BACKEND_PORT-8000}:80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    networks:
      - default

  celeryworker:
    image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: celeryworker.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - JOBS_BASE_PATH=${JOBS_BASE_PATH_MOUNT}
    volumes:
      - $JOBS_BASE_PATH_HOST:$JOBS_BASE_PATH_MOUNT
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    networks:
      - default

