version: 2.1


orbs:
  go: circleci/go@1.3.0
  docker: circleci/docker@1.4.0

jobs:
  build:

    docker:
      - image: "circleci/python:3.7"
      - image: circleci/postgres
        command: postgres -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off'
        environment:
          POSTGRES_USER: wikifactory
          POSTGRES_PASSWORD: wikipass
          POSTGRES_DB: dido
      - image: circleci/redis
    resource_class: large

    working_directory: ~/dido

    steps:

      - checkout
      - run:
          name: python VENV
          command: |
            sudo pip install pipenv
            pipenv install --pre --dev

      - run:
          name: Code formatting
          command: |
            pipenv run black --check .

      - run:
          name: Build using docker-compose
          command: |
            pipenv run docker-compose build

      - run:
          name: flake8
          command: |
            pipenv run flake8
      
      - run:
          name: unit-tests
          command: |
            pipenv run pytest --junitxml=../test-reports/tests.xml --cov wikifactory --cov-report html:../test-reports/htmlcov --cov-config .coveragerc -n 8
          when: always  # run even if there is a flake8 error

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports